name: Release CLI Binary

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          uv pip install -r pyproject.toml --extra build

      - name: Build Binary
        run: uvx shiv -c mezzosayshi -o mezzosayshi -p '/usr/bin/env python3' .

      - name: Upload Release Binary
        uses: softprops/action-gh-release@v2
        with:
          files: mezzosayshi
          token: ${{ secrets.MEZZOSAYSHI_GH_PAT }}
